### ISSUE TITLE
Simple, non-redux example improvements

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#138]
1. This should take props so as not to depend on the first ajax request: https://github.com/shakacode/react_on_rails/blob/master/app/assets/javascripts/react_on_rails.js#L159

2. We should not be passing empty props here:
<%= react_component('SimpleCommentScreen', {}, generator_function: false, prerender: false) %>

3. We need to break this up into a container component that does the Ajax call and a view component. 
See article on [Container Components](https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/app/components/SimpleCommentScreen.jsx). This is the file to break up: https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/app/components/SimpleCommentScreen.jsx

4. Change /app/assets/javascripts/application.js to not have rails specific startup code. See comment [here](https://github.com/shakacode/react-webpack-rails-tutorial/commit/d677265c6410fb481241c9cd114bf7dfff2dcef1#diff-a9c3bd311eab80c9ebe6a69830f9ad02R24)

@robwise We'll need to incorporate this into the generator.

@josiasds Would you like to take this one on?

**Comment by justin808** [comment]
This one is up for grabs until we assign somebody!

**Comment by robwise** [comment]
@justin808 I agree with this approach in general. While making the generators, I was having to first make my own custom apps in order to be sure that what I was generating would actually be a working app. The more we can make the tutorial the model on which to base our generators, the better. Obviously, there are some things in the tutorial that should not go in the generators, as the former is showing off and the latter is KISS. But things like the containers folder, the bundles folder, components using es2015 class syntax, etc. should all agree between the two.

**Comment by justin808** [comment]
@josiasds and @mamute Is this issue still valid?

**Comment by josiasds** [comment]
@justin808 Yes, we should break `SimpleCommentScreen` into a container to handle the requests and a view component.

**Comment by justin808** [comment]
@josiasds can we close this issue?

**Comment by josiasds** [comment]
@justin808 It looks like item 3 is still valid. `SimpleCommentScreen` is the only component that still doesn't follow the rules in the project. We have AJAX calls and HTML rendering together, and I think we should split it into a container and a view component. 

I'll try to take it this weekend.

**Comment by justin808** [comment]
@josiasds Can we close this one?
