### ISSUE TITLE
Switch to ES6 Class syntax for React from ES5 React.createClass

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#139]
@alexfedoseev will comment some more on the reasons we should do this.

Any volunteers for converting the code?

@robwise We'll be updating the generator to support this.

**Comment by rstudner** [comment]
I'll start on it tonight. Outside of cases using lonkedstatemixin, I've been doing es6 only react stuff and am familiar with he converting process.

**Comment by robwise** [comment]
@justin808 @rstudner this is implemented in https://github.com/shakacode/react_on_rails/pull/70 if you want to get an idea for what the syntax looks like. Note also that we are using a new paradigm in terms of `client/` folder organization.

For more on that, see this doc (soon to be included in the gem README): https://docs.google.com/a/friendsandguests.com/document/d/1jBrIjOfZ3ct8Uo2mzzwO0wCCkLtcl-fXyhgIFMKQitY/edit?usp=sharing

**Comment by rstudner** [comment]
It seems that the code is using es6 function syntax..  ala -- render() {  }  but is still using the React.createClass ES5 syntax (for say ,the helloworldcontainer).

Sorry, on mobile, hard to do markdown :)

**Comment by rstudner** [comment]
Thanks @robwise.  I think I have all the code updated above (i'd be a bit too aggressive in removing commas ;).  

I was having problems with the :: es7 binding syntax, so I used the ES6+/ES6 fat arrow function syntax.

I can revise it again if people really prefer it over the fat arrow (I guess I sort of like the fat arrow because it serves the same role as how coffeescript uses the fat arrow and more people might be familiar with it).

Either way is cool with me :)

**Comment by robwise** [comment]
@rstudner Yeah I didn't get the `::this` syntax until @jbhatab showed me it was exactly the same as doing `this.someMethod().bind(this)`. Basically, class methods by default have their `this` reference the class and not the actual component instance, so when we call methods from `render` (at which point `this` would refer to the component) we want to pass that binding so that the methods can access that component's `refs` and such.

I also wrote a couple of comments as I think it's considered better to not use the constructor if you don't need it. @alexfedoseev @jbhatab Can you comment on this?

We also changed the names of `ClientApp` and `ServerApp` to be `<DOMAIN>ClientEntryComponent` and `<DOMAIN>ServerEntryComponent`, respectively. <DOMAIN> being the name of each bundle inside of `app/bundles`. Again, if this is confusing, see that Google doc and take a look at this generated example prototype: https://github.com/shakacode/react_on_rails-generator-results/tree/redux-server-rendering/tester_app/client/app

**Comment by rstudner** [comment]
@robwise No, it isn't that :)  I get :: and .bind(this) from a technical perspective.  I'm just saying that if a person uses RubyMine as an IDE, it doesn't 'get' :: as ES6+/ES7 syntax and thus puts red underlines (i.e. "error indicators") all over the file and in the project tree/file view.  Just an eye-sore.  (I think the upcoming RubyMine 8 will resolve this).

Thus, I did => just to avoid 'that' in the short term.  But if people really wants :: syntax, then of course, I can put that in :)

re: Constructors - Sounds good & thanks for the heads up.  I had been using that syntax and 'missed the blog posting' regarding the best practice of not using them.  I can rip them out :)

**Comment by jbhatab** [comment]
@rstudner Get on that raw sublime life ;). I use the => syntax myself anyway because it makes passing data into functions easier imo. 

@robwise I don't use constructors anymore either. A few people have told me this is best practice.

**Comment by rstudner** [comment]
@jbhatab I love sublime and use it for doing react and Scala dev. I just know 20+ people who live in RubyMine. So I am always sensitive to their world :).

**Comment by jbhatab** [comment]
Fair enough. I actually really like the {(e) => this.onWhatever(e)} syntax.

**Comment by robwise** [comment]
@rstudner Oh sorry, I had misunderstood! Hmm, if this syntax is currently not supported in RM7, perhaps  F&G should change style to match not use it, then, and instead do it with either `=>` or `{(e) => this.onWhatever(e)}`.

Wondering what @alexfedoseev thinks on this one.

**Comment by rstudner** [comment]
Even outside of the RM7 issue I (personably) think the fat arrow syntax just reads easier. And as I alluded to way back - it mimics the coffee script syntax so lots of people make no mental shift lah lah.

**Comment by justin808** [comment]
I'm a big RubyMine user. Don't worry about the things like small markings of syntax errors and use the command line for linting. I tried to use RubyMine for that, but it's too much work to keep up with the command line tools.

**Comment by rstudner** [comment]
Good point @justin808. People can just disable the errors one at a time or wholesale to silence it.

**Comment by alexfedoseev** [comment]
Without fat arrows life is PAIN, especially in reducers:

```js
function(items) {
  return items.map(function(item) {
    return item * 2;
  });
}

/* VS */

items => items.map(item => item * 2)
```

**Comment by robwise** [comment]
@alexfedoseev So if you were doing it again, you would not use the `::this` syntax as you do in the F&G source code?

**Comment by alexfedoseev** [comment]
> So if you were doing it again, you would not use the ::this syntax as you do in the F&G source code?

@robwise It's different. Usecases:

```js
/* Fat arrows */

// without
_handleSubmit() {
  const { data } = this.props;
  apiCall({ data }).then(function(res) { this.setState({ ... }); }.bind(this));
                                                                   ^
//                                                             need bind to `this` here
}

// with
_handleSubmit() {
  const { data } = this.props;
  apiCall({ data }).then(res => this.setState({ ... })); // already bound to correct `this`
}
```

```js
/* Function bind */

// without
_handleSomething() { this.setState({ something }); }
<span onClick={this._handleSomething.bind(this)} />
// also we can bind all methods to `this` in constructor

// with
_handleSomething() { this.setState({ something }); }
<span onClick={::this._handleSomething} />
```

**Comment by rstudner** [comment]
I think there is even the other use case:

```
_handleSometing = () => {

}
```

This has the entire function bind correctly to 'this' (essentially what we got for free in the old ES5 syntax)

**Comment by alexfedoseev** [comment]
@rstudner :+1:

**Comment by alexfedoseev** [comment]
@rstudner Rewind :) Somehow it broke `this.setState`. Very likely I'll stick with `::functionBind` :)

**Comment by jbhatab** [comment]
@robwise I prefer to always bind my functions in the render, but is there any use case where you need to do it in the function itself?

Side note, this syntax actually broke for me with babel, dunno if they fixed it:
```
_handleSometing = () => {
}
```

@alexfedoseev how do you pass arguments into your functions? This is why I like the {(e)=> this._handleSomthing(pass, whatever)} because it gives you that flexibility. 

Also how do you guys feel about directly calling actions or prop functions in the render?

**Comment by rstudner** [comment]
You can do:
```
_handleSomething = (e, f) => {
}
```
etc.

As well, changing the initial state from constructor based to:
```
class CommentForm extends React.Component {
  formMode = 0;
  comment =  emptyComment;
```
simply results in the console error:
Uncaught TypeError: Cannot read property 'formMode' of null
for the code
```
 switch (this.state.formMode) {
```
I'll go ahead and just close this PR since 3 approaches have been 'wrong' for style reasons and once people decide on how code should 'look' we can move forward on it.
