### ISSUE TITLE
React Testing Libraries: Enzyme

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#169]
Anybody think we should be using this: 

https://github.com/airbnb/reagent

**Comment by josiasds** [comment]
Now it's called "Enzyme": https://github.com/airbnb/enzyme

**Comment by justin808** [comment]
@josiasds should we have any samples of this here? Maybe @mamute can help you?

**Comment by robwise** [comment]
@justin808 I've been discussing our JSX testing architecture with @alexfedoseev, this is actually kind of a complex issue because we are relying so heavily on webpack for our build, that when we run our tests straight from Node, we are having a lot of issues. For example, we use aliases in our webpack config to refer to the `lib` folder, we load our bootstrap overrides, we use css-modules, we use loaders to share styles, etc. 

All of that is webpack doing that, and when we run our tests from Node, all of that has to be re-implemented somehow. We may possibly need to move to Karma so that we can run our tests using webpack.

**Comment by alexfedoseev** [comment]
All issues, except share styles, are solved in my current branch on fng, so unit testing setup is quite good.

@justin808 I haven't used karma a lot (just setup once to see how it works). What do you thing about integration UI testing with it?

**Comment by justin808** [comment]
I've never used Karma, @alexfedoseev. I'm not clear on why we'd need it.

**Comment by justin808** [comment]
@alleycat-at-git Shall we close this as we prefer the new jest, correct?

**Comment by Judahmeek** [comment]
Facebook's examples combine Enzyme and Jest for DOM testing: https://facebook.github.io/jest/docs/tutorial-react.html#content

**Comment by robwise** [comment]
I don't see the benefit of Enzyme in the case of react_on_rails, we can just use Capybara for integration tests and Jest for quick sanity checks of the components' rendered HTML.

**Comment by robwise** [comment]
Just FYI on this, I do see some benefit where you need to test a complex interaction that is not part of a happy-path integration test. It's too costly and brittle to be checking all of that functionality in capybara. So I guess my position on this has "evolved" :)

**Comment by sdoxsee** [comment]
I'd like to use Jest & Enzyme with react on rails. I see the tutorial currently uses mocha. I'm pretty new to react on rails, react, babel, and webpack2 but I've had trouble figuring out how to get Jest & Enzyme recognizing ES6 with react on rails setup (I realize it's probably not related to react on rails specifics...but still would love to see an example if there was one). Is there an example that you know with Jest and react on rails? Thanks for this cool project! BTW, we're stuck on react on rails 8.x because we can't migrate to Rails 5 quite yet.

**Comment by justin808** [comment]
@sdoxsee RoR v10 does not require Rails v5.

**Comment by sdoxsee** [comment]
@justin808 my bad assumption on Rails v5. I think it's more the dependency tree ripples in our project from using the new webpacker. Thanks
