### ISSUE TITLE
Bug! Adding new comment does not go to top of list

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#188]
Repro:

1. Open two browser windows to http://reactrails.com
2. Add a name/comment to one.
3. You will see this show shortly on the other window, but not at the top
4. Also, the last comment gets moved down the list on the window where you added the comment.

**Comment by justin808** [comment]
@mamute Any chance you want to take a look at this?

**Comment by mamute** [comment]
@justin808 yes! doing this right now :)

**Comment by adavkay** [comment]
Is this still an issue? I tested quick and it appeared to be working.

**Comment by mamute** [comment]
Yes, not easy to reproduce. But i'm working on a fix to this...

Em segunda-feira, 4 de janeiro de 2016, Andy Kay <notifications@github.com>
escreveu:

> Is this still an issue? I tested quick and it appeared to be working.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shakacode/react-webpack-rails-tutorial/issues/188#issuecomment-168674813>
> .
>


-- 

------------------------------------
Marcus Sá
about.me/marcus_sa | marcus.m.sa@gmail.com

**Comment by adavkay** [comment]
Any additional steps to reproduce worth mentioning?

**Comment by mamute** [comment]
Not that I know. I only reproduce the bug on the remote server, not locally

**Comment by justin808** [comment]
@adavkay @mamute The key is that we're explicitly keeping a sorted order.

**Comment by adavkay** [comment]
Hey guys I think I may have found the issue! I had a few spare moments today so I pulled the code base down and started to try and repro the issue locally with no luck. I thought it may have something to do with pushing the submitted comment into the Immutable list of comments and then merging the next fetch of comments from the server. I got nowhere with that.

Finally I was able to consistently repro the issue on the live server on reactrails.com and noticed that the created_at timetamps were out of order so then I thought maybe it was a weird timezone setting on the server because I live way up in northern freaking Maine!

But then I noticed that the id attribute was out of order for some comments as well. Not very haphazardly, but in blocks; all my comments were being returned from the server in sequential order.

I thought that was really odd so I googled:

```
ruby on rails model.all out of order
```

And found this interesting Stack Overflow post: http://stackoverflow.com/questions/4986496/activerecord-find-all-not-sorting-by-id

Apparently ordering by ID is not guaranteed by default. We can fix this by either setting a default scope:

```ruby
default_scope order('id ASC')
```

or by calling:

```ruby
Model.order('id ASC')
```

I'm a Ruby and RoR noob so I'm not sure which one you guys would rather implement but if I am correct about this ( I could be totally wrong ) I would be super stoked if I could submit a PR as this would be my first ever pull request!

**Comment by justin808** [comment]
@adavkay We'd be stoked for you to submit a PR. Possibly talk to @mamute as he was also looking at this one. I invited you to our our private Slack room for easier discussions! Thanks!

**Comment by justin808** [comment]
@adavkay In general, you want to avoid default scopes.

Also, we need to clarify in the API if we send the items in chron or reverse chron order. It doesn't make sense to sort chron on the server and the reorder on the client.

**Comment by adavkay** [comment]
@justin808 ok sounds good. I'll wait to hear from @mamute before I submit a PR. As for the ordering, we could send the comments in reverse chron straight from the server instead of reversing the comment list every render on the client. Just have to remember to unshift instead of push in the `SUBMIT_COMMENT_SUCCESS` case of the `commentsReducer`.

**Comment by mamute** [comment]
@adavkay @justin808 I already did the changes that @adavkay mentioned. To complete the fix I only have to change one test that tests the reverse order of CommentList. I also changed the SimpleCommentScreen that insert the comment at the end of the list too. I'll submit the PR in some minutes...

**Comment by mamute** [comment]
Done #194
