### ISSUE TITLE
File organization

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#208]
Considerations:

move https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/app/bundles/comments/store/commentsStore.js

over to the startup directory

and rename file as commentsStoreCreator.js

CC: @alexfedoseev

**Comment by robwise** [comment]
@justin808 @alexfedoseev why are we reinventing the wheel here? We have ReactOnRails specific code, it goes in the `startup` folder. Otherwise, we just do what the convention for Redux apps is: https://github.com/rackt/redux/tree/master/examples/todomvc/store

It's called `configureStore` and it goes in its own `store` folder.

**Comment by justin808** [comment]
6 of one, half dozen of other

`configureStore` is good

**Comment by robwise** [comment]
:+1:
