### ISSUE TITLE
Upgrade to Bootstrap 4, including example of font-awesome-loader

### ISSUE THREAD

**Issue by justin808** [shakacode/react-webpack-rails-tutorial#238]
Once this gets merged: https://github.com/shakacode/bootstrap-loader/pull/56

Then we can create a branch to update from Bootstrap 3 to Bootstrap 4.

We should also show an example of using font-awesome with the [font-awesome-loader](https://github.com/shakacode/font-awesome-loader).

**Comment by abhishekbose87** [comment]
@justin808 Hi, I wanted to take a jab at this one. Can I take this up ?

**Comment by justin808** [comment]
@abhishekbose87 Sure!

**Comment by abhishekbose87** [comment]
@justin808 I got the build to pass. Now I am trying to get the design as much as possible as the previous one.
But there are some issues which are cropping up (which I think will be fixed with the beta release)
For eg. http://stackoverflow.com/questions/33486653/stacked-collapsible-navbar-in-bootstrap-4

Please advise whether I should go ahead with custom fixes for such issues.

**Comment by justin808** [comment]
I'm open to that. Let's make a PR and I'll try it out!

**Comment by justin808** [comment]
Let's get this updated, now that https://github.com/shakacode/bootstrap-loader is updated.

**Comment by SuperSoftDev** [comment]
Hi.
I am grabbing this one as the next step of my application.

**Comment by SuperSoftDev** [comment]
how should I do?

**Comment by agarwalakash** [comment]
Hello, 
I am grabbing this issue.

**Comment by vtamara** [comment]
I sent PR #498 to close this issue.

**Comment by ahangarha** [comment]
We will migrate to Tailwind CSS.
