### ISSUE TITLE
Recommended way to manage CSS assets?

### ISSUE THREAD

**Issue by samphilipd** [shakacode/react-webpack-rails-tutorial#258]
Hey guys,

The project is great! Really excited to use this. I have one question - what is the recommended way to handle CSS assets?

I would ideally like to do this using bower, but not sure how to integrate that with the build pipeline in react_on_rails. It seems like bootstrap has special support, but I want to use [bourbon](http://bourbon.io/) instead.

I can include the gem... but then it won't be available as an asset when running the client apps in isolation - how can I address this? What if I want to use bower or npm to manage CSS assets?

**Comment by justin808** [comment]
@samphilipd This is probably a better discussion for http://forum.shakacode.com. 

1. The **simple way** is to only use [react_on_rails](https://github.com/shakacode/react_on_rails/) for JS assets, and not CSS/images, etc. This is super simple. You use standard rails techniques.
2. The **webpack way** is to use webpack to generate assets. This project uses that technique. 

I wrote up a detailed response here:

https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/recommended-project-structure.md#css-sass-fonts-and-images

Anything that I'm missing?

**Comment by ramusus** [comment]
@justin808 How to deal with [Rails assets fingerprinting](http://guides.rubyonrails.org/asset_pipeline.html#what-is-fingerprinting-and-why-should-i-care-questionmark) technique using webpack way? In tutorial you are using small image, which content is stored inside CSS file completely. If we change it to bigger image (~>10Kb), CSS file will link to the external file `image.jpg`, instead of content. But rails assets pipeline will transform the file name to `image-5dd0219..........52.jpg` and image will be unaccessible. This problem described more here https://github.com/shakacode/react_on_rails/issues/401

**Comment by ramusus** [comment]
Solved my issue with images assets very simple - just put images to public folder and fingerprinting is not worrying me.

**Comment by justin808** [comment]
We're about to ship with https://github.com/shakacode/react_on_rails/pull/413.

That handles the problems of images when using webpack for CSS assets with Rails!
