### ISSUE TITLE
How do AJAX requests function when the node server and rails servers are on different ports?

### ISSUE THREAD

**Issue by jasongonzales23** [shakacode/react-webpack-rails-tutorial#92]
EOM

**Comment by justin808** [comment]
We don't use different ports. We simply use webpack to create a nice JS file that slips into the asset pipeline.

**Comment by justin808** [comment]
@alexfedoseev, on the team, wrote this awesome [article](https://medium.com/@alexfedoseev/isomorphic-react-with-rails-part-i-440754e82a59) which explains an alternative solution that uses a node server on different ports. It adds a lot of complexity. The way presented here is super simple. We might consider integrating webpack more closely so that you can get hot reloading within rails, *someday*. Not a priority. Be sure to checkout https://github.com/shakacode/react_on_rails.

**Comment by jasongonzales23** [comment]
Thanks so much for the quick response! I guess I should have asked my question more clearly though. Let's say I want to use hot reloading while using the webpack dev server and my component hits the api on my Rails server (much like your Comment component does). Is this possible with your setup?

**Comment by justin808** [comment]
@jasongonzales23 Please see these two issues:

* https://github.com/shakacode/react_on_rails/issues/18
* https://github.com/danott/webpack_rails/issues/12

It would be amazing if you could take the lead and see how we could get this integrated into the tutorial and/or react_on_rails gem.

**Comment by justin808** [comment]
And here's another article on the topic: http://clarkdave.net/2015/01/how-to-use-webpack-with-rails/

**Comment by jasongonzales23** [comment]
Justin,

I will gladly take a crack at 'em!

**Comment by justin808** [comment]
@jasongonzales23 I submitted issue: https://github.com/shakacode/react_on_rails/issues/26 You might have fun experimenting with converting some code from the article into helpers in the react_on_rails gem.
